/* PlSqlTokenManager.java */
/* Generated By:JJTree&JavaCC: Do not edit this line. PlSqlTokenManager.java */
package parser;
import java.io.Reader;
import java.io.FileInputStream;
import java.util.HashSet;
import java.util.Set;

/** Token Manager. */
@SuppressWarnings("unused")public class PlSqlTokenManager implements PlSqlConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0, long active1, long active2){
   switch (pos)
   {
      case 0:
         if ((active2 & 0x1000000000L) != 0L)
            return 0;
         if ((active0 & 0xffffffffffffffe0L) != 0L || (active1 & 0xffffffffffffffffL) != 0L || (active2 & 0x3ffL) != 0L)
         {
            jjmatchedKind = 144;
            return 68;
         }
         if ((active2 & 0x1000400800000L) != 0L)
            return 69;
         if ((active2 & 0x20400000L) != 0L)
            return 18;
         if ((active2 & 0x8000000000L) != 0L)
            return 3;
         return -1;
      case 1:
         if ((active0 & 0x1ffffdfffff79e0L) != 0L || (active1 & 0xfdffffffffe47ff8L) != 0L || (active2 & 0x3ffL) != 0L)
         {
            if (jjmatchedPos != 1)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 1;
            }
            return 68;
         }
         if ((active0 & 0xfe00002000008600L) != 0L || (active1 & 0x2000000001b8007L) != 0L)
            return 68;
         return -1;
      case 2:
         if ((active0 & 0x60100000005a0L) != 0L || (active1 & 0x4010860800200400L) != 0L)
            return 68;
         if ((active1 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 2;
            }
            return 11;
         }
         if ((active0 & 0xf9f9fedfffff7840L) != 0L || (active1 & 0xbdef79f7dfd67bfdL) != 0L || (active2 & 0x3ffL) != 0L)
         {
            if (jjmatchedPos != 2)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 2;
            }
            return 68;
         }
         return -1;
      case 3:
         if ((active0 & 0x584048400f0000L) != 0L || (active1 & 0x184040300463079L) != 0L || (active2 & 0x198L) != 0L)
            return 68;
         if ((active0 & 0xf9a5be97bff07840L) != 0L || (active1 & 0xbc6b79f4df904b84L) != 0L || (active2 & 0x267L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 3;
            }
            return 68;
         }
         if ((active1 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 3)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 3;
            }
            return 11;
         }
         return -1;
      case 4:
         if ((active1 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 4;
            return 11;
         }
         if ((active0 & 0xe1243e17bfe07000L) != 0L || (active1 & 0x340a797417804a04L) != 0L || (active2 & 0x7L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 4;
            return 68;
         }
         if ((active0 & 0x1881808000100840L) != 0L || (active1 & 0x88610080c8102180L) != 0L || (active2 & 0x260L) != 0L)
            return 68;
         return -1;
      case 5:
         if ((active1 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 5;
            }
            return 11;
         }
         if ((active0 & 0x2104220420c00000L) != 0L || (active1 & 0x3000283404004800L) != 0L || (active2 & 0x1L) != 0L)
            return 68;
         if ((active0 & 0xc0201c139f207000L) != 0L || (active1 & 0x40a514013800204L) != 0L || (active2 & 0x6L) != 0L)
         {
            if (jjmatchedPos != 5)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 5;
            }
            return 68;
         }
         return -1;
      case 6:
         if ((active0 & 0x80201c100e800000L) != 0L || (active1 & 0x40a512013000004L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 6;
            }
            return 68;
         }
         if ((active0 & 0x4000000391205000L) != 0L || (active1 & 0x4000800200L) != 0L || (active2 & 0x6L) != 0L)
            return 68;
         if ((active0 & 0x2000L) != 0L || (active1 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 6)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 6;
            }
            return 11;
         }
         return -1;
      case 7:
         if ((active0 & 0x2000L) != 0L || (active1 & 0x20000000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 7;
            return 11;
         }
         if ((active0 & 0x80001c000c800000L) != 0L || (active1 & 0x400502011000004L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 7;
            return 68;
         }
         if ((active0 & 0x20001002000000L) != 0L || (active1 & 0xa010002000000L) != 0L)
            return 68;
         if ((active2 & 0x2L) != 0L)
            return 11;
         return -1;
      case 8:
         if ((active0 & 0x2000L) != 0L || (active1 & 0x20000000L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 8;
            }
            return 11;
         }
         if ((active0 & 0x80001c0000800000L) != 0L || (active1 & 0x102011000004L) != 0L)
            return 68;
         if ((active0 & 0xc000000L) != 0L || (active1 & 0x400400000000000L) != 0L)
         {
            if (jjmatchedPos != 8)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 8;
            }
            return 68;
         }
         return -1;
      case 9:
         if ((active1 & 0x400400000000000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 9;
            }
            return 68;
         }
         if ((active0 & 0xc000000L) != 0L)
            return 68;
         if ((active1 & 0x20000000L) != 0L)
            return 11;
         if ((active0 & 0x80000002000L) != 0L)
         {
            if (jjmatchedPos != 9)
            {
               jjmatchedKind = 144;
               jjmatchedPos = 9;
            }
            return 11;
         }
         return -1;
      case 10:
         if ((active1 & 0x400000000000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 10;
            return 68;
         }
         if ((active0 & 0x80000002000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 10;
            return 11;
         }
         if ((active0 & 0x8000000L) != 0L || (active1 & 0x400000000000000L) != 0L)
            return 68;
         return -1;
      case 11:
         if ((active0 & 0x80000002000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 11;
            return 11;
         }
         if ((active1 & 0x400000000000L) != 0L)
            return 68;
         return -1;
      case 12:
         if ((active0 & 0x80000002000L) != 0L)
         {
            jjmatchedKind = 144;
            jjmatchedPos = 12;
            return 11;
         }
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0, long active1, long active2){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0, active1, active2), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         return jjStopAtPos(0, 170);
      case 35:
         return jjStopAtPos(0, 171);
      case 37:
         jjmatchedKind = 169;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0xc0000000L);
      case 40:
         return jjStopAtPos(0, 154);
      case 41:
         return jjStopAtPos(0, 155);
      case 42:
         jjmatchedKind = 166;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x10000000000L);
      case 43:
         return jjStopAtPos(0, 163);
      case 44:
         return jjStopAtPos(0, 156);
      case 45:
         return jjStartNfaWithStates_0(0, 164, 0);
      case 46:
         jjmatchedKind = 151;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x1000400000000L);
      case 47:
         return jjStartNfaWithStates_0(0, 167, 3);
      case 58:
         jjmatchedKind = 150;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x20000000L);
      case 59:
         return jjStopAtPos(0, 153);
      case 60:
         jjmatchedKind = 173;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x100000000L);
      case 61:
         jjmatchedKind = 152;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x800000000000L);
      case 62:
         jjmatchedKind = 172;
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x200000000L);
      case 64:
         return jjStopAtPos(0, 174);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa1_0(0x7e0L, 0x0L, 0x0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa1_0(0xf800L, 0x0L, 0x0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa1_0(0x3fff0000L, 0x0L, 0x0L);
      case 68:
      case 100:
         return jjMoveStringLiteralDfa1_0(0x3fc0000000L, 0x0L, 0x0L);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa1_0(0x7fc000000000L, 0x0L, 0x0L);
      case 70:
      case 102:
         return jjMoveStringLiteralDfa1_0(0x3f800000000000L, 0x0L, 0x0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa1_0(0xc0000000000000L, 0x0L, 0x0L);
      case 72:
      case 104:
         return jjMoveStringLiteralDfa1_0(0x100000000000000L, 0x0L, 0x0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa1_0(0xfe00000000000000L, 0x7L, 0x0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x78L, 0x0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x180L, 0x0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7e00L, 0x0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7f8000L, 0x0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3f800000L, 0x0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7ffc0000000L, 0x0L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x3ff80000000000L, 0x0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x7c0000000000000L, 0x0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa1_0(0x0L, 0xf800000000000000L, 0x0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x7L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x3f8L);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x0L, 0x0L, 0x2000000000L);
      default :
         return jjMoveNfa_0(2, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0, long active1, long active2){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0, active1, active2);
      return 1;
   }
   switch(curChar)
   {
      case 42:
         if ((active2 & 0x10000000000L) != 0L)
            return jjStopAtPos(1, 168);
         else if ((active2 & 0x1000000000000L) != 0L)
            return jjStopAtPos(1, 176);
         break;
      case 46:
         if ((active2 & 0x400000000L) != 0L)
            return jjStopAtPos(1, 162);
         break;
      case 60:
         if ((active2 & 0x100000000L) != 0L)
            return jjStopAtPos(1, 160);
         break;
      case 61:
         if ((active2 & 0x20000000L) != 0L)
            return jjStopAtPos(1, 157);
         break;
      case 62:
         if ((active2 & 0x200000000L) != 0L)
            return jjStopAtPos(1, 161);
         else if ((active2 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 175);
         break;
      case 65:
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x100000040070000L, active1, 0x401800c1800200L, active2, 0xfL);
      case 69:
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x800f80001800L, active1, 0x80e07f00000088L, active2, 0L);
      case 70:
      case 102:
         if ((active0 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 57, 68);
         else if ((active1 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 79, 68);
         break;
      case 72:
      case 104:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000L, active1, 0x101000000000000L, active2, 0x70L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000002000L, active1, 0x2008000000110L, active2, 0x80L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x4000000000000L, active2, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa2_0(active0, 0x100c000100060L, active1, 0L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x8000000000000L, active2, 0L);
      case 78:
      case 110:
         if ((active0 & 0x400000000000000L) != 0L)
         {
            jjmatchedKind = 58;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x10000L) != 0L)
         {
            jjmatchedKind = 80;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0xf800010000000180L, active1, 0x1800000000020001L, active2, 0L);
      case 79:
      case 111:
         if ((active0 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 37, 68);
         else if ((active1 & 0x200000000000000L) != 0L)
            return jjStartNfaWithStates_0(1, 121, 68);
         return jjMoveStringLiteralDfa2_0(active0, 0x4600000fe04000L, active1, 0x70002000c60L, active2, 0x100L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x2000000000040000L, active2, 0L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x10000000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active1 & 0x80000L) != 0L)
         {
            jjmatchedKind = 83;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x88000000000000L, active1, 0x40000001c100000L, active2, 0x80000200L);
      case 83:
      case 115:
         if ((active0 & 0x200L) != 0L)
         {
            jjmatchedKind = 9;
            jjmatchedPos = 1;
         }
         else if ((active1 & 0x2L) != 0L)
         {
            jjmatchedKind = 65;
            jjmatchedPos = 1;
         }
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000400L, active1, 0xc000000000000004L, active2, 0L);
      case 84:
      case 116:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x20000000000000L, active2, 0x40000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x30000030000000L, active1, 0x207000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa2_0(active0, 0L, active1, 0x400000L, active2, 0L);
      case 88:
      case 120:
         return jjMoveStringLiteralDfa2_0(active0, 0x7c0000000000L, active1, 0x20000000L, active2, 0L);
      case 89:
      case 121:
         if ((active0 & 0x8000L) != 0L)
            return jjStartNfaWithStates_0(1, 15, 68);
         break;
      case 124:
         if ((active2 & 0x2000000000L) != 0L)
            return jjStopAtPos(1, 165);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0, active1, active2);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(0, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0, active1, active2);
      return 2;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x20000000L, active2, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa3_0(active0, 0x80000L, active1, 0x429000304000000L, active2, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x42000000000000L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(2, 10, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0x1e0180000000L, active1, 0x400800020L, active2, 0L);
      case 68:
      case 100:
         if ((active0 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(2, 7, 68);
         else if ((active0 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 40, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0x800000000000000L, active1, 0x2000000000100000L, active2, 0L);
      case 69:
      case 101:
         if ((active1 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 126, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x100000000440000L, active2, 0x30L);
      case 70:
      case 102:
         if ((active1 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(2, 99, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0x200000000L, active1, 0x8L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa3_0(active0, 0x800L, active1, 0x8000000000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa3_0(active0, 0x600000000000L, active1, 0x9804000048000000L, active2, 0x248L);
      case 75:
      case 107:
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x10L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(2, 5, 68);
         else if ((active1 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 116, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0x10000400010000L, active1, 0x210000023000L, active2, 0x1L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa3_0(active0, 0xe00000L, active1, 0x80000004000L, active2, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa3_0(active0, 0x102000000f002000L, active1, 0x80000100L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x89000000104000L, active1, 0x10000044L, active2, 0x80000000L);
      case 82:
      case 114:
         if ((active0 & 0x2000000000000L) != 0L)
         {
            jjmatchedKind = 49;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0x4000030000000L, active1, 0x400001000080L, active2, 0x106L);
      case 83:
      case 115:
         return jjMoveStringLiteralDfa3_0(active0, 0x200000d800060000L, active1, 0x80000002000000L, active2, 0L);
      case 84:
      case 116:
         if ((active1 & 0x400L) != 0L)
            return jjStartNfaWithStates_0(2, 74, 68);
         else if ((active1 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(2, 85, 68);
         else if ((active1 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(2, 111, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0xc040800040001040L, active1, 0x3000000201L, active2, 0x80L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa3_0(active0, 0x100000000000000L, active1, 0x104000000000L, active2, 0L);
      case 87:
      case 119:
         if ((active1 & 0x20000000000L) != 0L)
         {
            jjmatchedKind = 105;
            jjmatchedPos = 2;
         }
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0x40000000800L, active2, 0L);
      case 89:
      case 121:
         if ((active0 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(2, 8, 68);
         return jjMoveStringLiteralDfa3_0(active0, 0L, active1, 0L, active2, 0x40000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0, active1, active2);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(1, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0, active1, active2);
      return 3;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x5020200002000L, active1, 0x2000000000000800L, active2, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x4000L, active2, 0L);
      case 67:
      case 99:
         if ((active0 & 0x800000000L) != 0L)
            return jjStartNfaWithStates_0(3, 35, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x20800000000000L, active1, 0x10000000L, active2, 0x6L);
      case 68:
      case 100:
         if ((active1 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(3, 96, 68);
         break;
      case 69:
      case 101:
         if ((active0 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 17, 68);
         else if ((active0 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(3, 30, 68);
         else if ((active0 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 38, 68);
         else if ((active1 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 68, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0xf8000c0400000040L, active1, 0x304000100000L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0xa4000080L, active2, 0L);
      case 72:
      case 104:
         if ((active2 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(3, 135, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x8000000000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa4_0(active0, 0x100008080000800L, active1, 0x400002000000L, active2, 0L);
      case 75:
      case 107:
         if ((active1 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(3, 69, 68);
         else if ((active2 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(3, 136, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800000L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x10000L) != 0L)
            return jjStartNfaWithStates_0(3, 16, 68);
         else if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 52, 68);
         else if ((active1 & 0x1000L) != 0L)
         {
            jjmatchedKind = 76;
            jjmatchedPos = 3;
         }
         else if ((active1 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(3, 97, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x100100004000L, active1, 0x4a010000002004L, active2, 0x40L);
      case 77:
      case 109:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 51, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0xe00000L, active1, 0L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 82, 68);
         else if ((active1 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 120, 68);
         else if ((active2 & 0x10L) != 0L)
            return jjStartNfaWithStates_0(3, 132, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000L, active1, 0x8400000000000000L, active2, 0L);
      case 79:
      case 111:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 54, 68);
         else if ((active1 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(3, 64, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x800000408000000L, active2, 0L);
      case 80:
      case 112:
         if ((active1 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(3, 70, 68);
         else if ((active1 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 114, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x80000000000L, active2, 0x40000000L);
      case 81:
      case 113:
         return jjMoveStringLiteralDfa4_0(active0, 0L, active1, 0x1000000000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x80000L) != 0L)
            return jjStartNfaWithStates_0(3, 19, 68);
         else if ((active1 & 0x400000L) != 0L)
            return jjStartNfaWithStates_0(3, 86, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000L, active1, 0x21000000000000L, active2, 0x20L);
      case 83:
      case 115:
         if ((active1 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 106, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x20002e100000L, active1, 0x40000000L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x40000L) != 0L)
            return jjStartNfaWithStates_0(3, 18, 68);
         else if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 46, 68);
         else if ((active1 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 67, 68);
         else if ((active1 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 119, 68);
         else if ((active2 & 0x8L) != 0L)
            return jjStartNfaWithStates_0(3, 131, 68);
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000L, active1, 0x1000000L, active2, 0x200L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000000L, active1, 0x3000000300L, active2, 0x1L);
      case 87:
      case 119:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000L, active1, 0L, active2, 0x80000000L);
      case 89:
      case 121:
         if ((active1 & 0x20000L) != 0L)
            return jjStartNfaWithStates_0(3, 81, 68);
         break;
      default :
         break;
   }
   return jjStartNfa_0(2, active0, active1, active2);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(2, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0, active1, active2);
      return 4;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000L, active1, 0x400000800004L, active2, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x10000000000L, active2, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x200000000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 20, 68);
         else if ((active1 & 0x80L) != 0L)
            return jjStartNfaWithStates_0(4, 71, 68);
         else if ((active1 & 0x40000000L) != 0L)
            return jjStartNfaWithStates_0(4, 94, 68);
         else if ((active1 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(4, 95, 68);
         else if ((active1 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 112, 68);
         else if ((active1 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 118, 68);
         else if ((active2 & 0x20L) != 0L)
            return jjStartNfaWithStates_0(4, 133, 68);
         else if ((active2 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 134, 68);
         else if ((active2 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(4, 137, 68);
         else if ((active2 & 0x40000000L) != 0L)
            return jjStopAtPos(4, 158);
         return jjMoveStringLiteralDfa5_0(active0, 0x11205000L, active1, 0x10004000L, active2, 0x1L);
      case 70:
      case 102:
         if ((active0 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 39, 68);
         break;
      case 71:
      case 103:
         if ((active1 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 127, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000000L, active1, 0L, active2, 0L);
      case 72:
      case 104:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 47, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0L, active2, 0x6L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x1000c00000L, active1, 0x2000001000800L, active2, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L, active1, 0x8080000000000L, active2, 0L);
      case 77:
      case 109:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000L, active1, 0x4000000L, active2, 0L);
      case 78:
      case 110:
         if ((active0 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(4, 11, 68);
         else if ((active1 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 123, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000000L, active1, 0L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa5_0(active0, 0x20000000L, active1, 0L, active2, 0L);
      case 80:
      case 112:
         if ((active0 & 0x80000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 55, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0xe0000000000L, active1, 0x100000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x40L) != 0L)
            return jjStartNfaWithStates_0(4, 6, 68);
         else if ((active0 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 60, 68);
         else if ((active1 & 0x100000L) != 0L)
            return jjStartNfaWithStates_0(4, 84, 68);
         else if ((active1 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(4, 91, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0xa000000000002000L, active1, 0x7420000200L, active2, 0L);
      case 83:
      case 115:
         if ((active1 & 0x100L) != 0L)
            return jjStartNfaWithStates_0(4, 72, 68);
         else if ((active1 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(4, 77, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0L, active1, 0x400000000000000L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 48, 68);
         else if ((active1 & 0x8000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 103, 68);
         else if ((active1 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 117, 68);
         return jjMoveStringLiteralDfa5_0(active0, 0x2020040e000000L, active1, 0x2000000002000000L, active2, 0x80000000L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa5_0(active0, 0x100200000000L, active1, 0x1000000000000000L, active2, 0L);
      case 88:
      case 120:
         if ((active0 & 0x800000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 59, 68);
         break;
      default :
         break;
   }
   return jjStartNfa_0(3, active0, active1, active2);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(3, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0, active1, active2);
      return 5;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         if ((active1 & 0x4000000L) != 0L)
            return jjStartNfaWithStates_0(5, 90, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0x82004000L, active1, 0x400010020000200L, active2, 0x6L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x1000000L, active1, 0L, active2, 0L);
      case 68:
      case 100:
         if ((active1 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 98, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x400000000L) != 0L)
            return jjStartNfaWithStates_0(5, 34, 68);
         else if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 41, 68);
         else if ((active1 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 107, 68);
         else if ((active1 & 0x1000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 124, 68);
         else if ((active1 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 125, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000001000L, active1, 0L, active2, 0L);
      case 71:
      case 103:
         if ((active0 & 0x100000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 56, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x800000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000000L, active1, 0x8000002000000L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 50, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0x200000000L, active1, 0x400000000000L, active2, 0L);
      case 78:
      case 110:
         if ((active1 & 0x1000000000L) != 0L)
         {
            jjmatchedKind = 100;
            jjmatchedPos = 5;
         }
         return jjMoveStringLiteralDfa6_0(active0, 0x1010200000L, active1, 0x2002000000000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0L, active1, 0x100000000000L, active2, 0L);
      case 82:
      case 114:
         if ((active0 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(5, 29, 68);
         else if ((active1 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(5, 78, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0x10c000000L, active1, 0L, active2, 0L);
      case 83:
      case 115:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 45, 68);
         else if ((active2 & 0x1L) != 0L)
            return jjStartNfaWithStates_0(5, 128, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0x8000100000000000L, active1, 0x4000000000L, active2, 0L);
      case 84:
      case 116:
         if ((active0 & 0x400000L) != 0L)
         {
            jjmatchedKind = 22;
            jjmatchedPos = 5;
         }
         else if ((active0 & 0x2000000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 61, 68);
         else if ((active1 & 0x800L) != 0L)
            return jjStartNfaWithStates_0(5, 75, 68);
         else if ((active1 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 109, 68);
         return jjMoveStringLiteralDfa6_0(active0, 0xc0000800000L, active1, 0x1000004L, active2, 0L);
      case 89:
      case 121:
         return jjMoveStringLiteralDfa6_0(active0, 0x2000L, active1, 0L, active2, 0x80000000L);
      default :
         break;
   }
   return jjStartNfa_0(4, active0, active1, active2);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(4, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0, active1, active2);
      return 6;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa7_0(active0, 0x2000L, active1, 0L, active2, 0L);
      case 65:
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0xc000000L, active1, 0L, active2, 0L);
      case 67:
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x1000000000L, active1, 0x400010000000000L, active2, 0L);
      case 69:
      case 101:
         if ((active0 & 0x100000000L) != 0L)
            return jjStartNfaWithStates_0(6, 32, 68);
         else if ((active1 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(6, 87, 68);
         else if ((active1 & 0x4000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 102, 68);
         return jjMoveStringLiteralDfa7_0(active0, 0x8000000000000000L, active1, 0L, active2, 0L);
      case 71:
      case 103:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000000000000L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa7_0(active0, 0x1c0000000000L, active1, 0x502001000004L, active2, 0L);
      case 76:
      case 108:
         if ((active0 & 0x80000000L) != 0L)
            return jjStartNfaWithStates_0(6, 31, 68);
         else if ((active1 & 0x200L) != 0L)
            return jjStartNfaWithStates_0(6, 73, 68);
         break;
      case 78:
      case 110:
         if ((active0 & 0x1000L) != 0L)
            return jjStartNfaWithStates_0(6, 12, 68);
         else if ((active0 & 0x4000L) != 0L)
            return jjStartNfaWithStates_0(6, 14, 68);
         return jjMoveStringLiteralDfa7_0(active0, 0x2000000L, active1, 0x8000020000000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa7_0(active0, 0x20000000000000L, active1, 0L, active2, 0L);
      case 80:
      case 112:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x80000000L);
      case 82:
      case 114:
         if ((active0 & 0x4000000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 62, 68);
         else if ((active2 & 0x4L) != 0L)
         {
            jjmatchedKind = 130;
            jjmatchedPos = 6;
         }
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0L, active2, 0x2L);
      case 84:
      case 116:
         if ((active0 & 0x200000L) != 0L)
            return jjStartNfaWithStates_0(6, 21, 68);
         else if ((active0 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(6, 24, 68);
         else if ((active0 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(6, 28, 68);
         else if ((active0 & 0x200000000L) != 0L)
            return jjStartNfaWithStates_0(6, 33, 68);
         return jjMoveStringLiteralDfa7_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa7_0(active0, 0L, active1, 0x2000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0, active1, active2);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(5, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0, active1, active2);
      return 7;
   }
   switch(curChar)
   {
      case 50:
         if ((active2 & 0x2L) != 0L)
            return jjStartNfaWithStates_0(7, 129, 11);
         break;
      case 67:
      case 99:
         return jjMoveStringLiteralDfa8_0(active0, 0x8000000000000000L, active1, 0L, active2, 0L);
      case 69:
      case 101:
         if ((active1 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 89, 68);
         else if ((active2 & 0x80000000L) != 0L)
            return jjStopAtPos(7, 159);
         return jjMoveStringLiteralDfa8_0(active0, 0x800000L, active1, 0L, active2, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0xc002000L, active1, 0L, active2, 0L);
      case 75:
      case 107:
         if ((active1 & 0x10000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 104, 68);
         break;
      case 78:
      case 110:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 53, 68);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x102000000000L, active2, 0L);
      case 79:
      case 111:
         return jjMoveStringLiteralDfa8_0(active0, 0xc0000000000L, active1, 0x1000004L, active2, 0L);
      case 82:
      case 114:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x10000000L, active2, 0L);
      case 83:
      case 115:
         if ((active1 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 113, 68);
         break;
      case 84:
      case 116:
         if ((active0 & 0x2000000L) != 0L)
            return jjStartNfaWithStates_0(7, 25, 68);
         else if ((active0 & 0x1000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 36, 68);
         else if ((active1 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(7, 115, 68);
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400000000000000L, active2, 0L);
      case 85:
      case 117:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x20000000L, active2, 0L);
      case 86:
      case 118:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000000L, active1, 0L, active2, 0L);
      case 90:
      case 122:
         return jjMoveStringLiteralDfa8_0(active0, 0L, active1, 0x400000000000L, active2, 0L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0, active1, active2);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0, long old1, long active1, long old2, long active2){
   if (((active0 &= old0) | (active1 &= old1) | (active2 &= old2)) == 0L)
      return jjStartNfa_0(6, old0, old1, old2);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0, active1, 0L);
      return 8;
   }
   switch(curChar)
   {
      case 65:
      case 97:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400000000000L);
      case 68:
      case 100:
         if ((active0 & 0x800000L) != 0L)
            return jjStartNfaWithStates_0(8, 23, 68);
         break;
      case 69:
      case 101:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 44, 68);
         else if ((active1 & 0x10000000L) != 0L)
            return jjStartNfaWithStates_0(8, 92, 68);
         break;
      case 71:
      case 103:
         if ((active1 & 0x2000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 101, 68);
         break;
      case 73:
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x400000000000000L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa9_0(active0, 0L, active1, 0x20000000L);
      case 78:
      case 110:
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 42;
            jjmatchedPos = 8;
         }
         else if ((active1 & 0x4L) != 0L)
            return jjStartNfaWithStates_0(8, 66, 68);
         else if ((active1 & 0x1000000L) != 0L)
            return jjStartNfaWithStates_0(8, 88, 68);
         return jjMoveStringLiteralDfa9_0(active0, 0x8000c002000L, active1, 0L);
      case 84:
      case 116:
         if ((active0 & 0x8000000000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 63, 68);
         else if ((active1 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 108, 68);
         break;
      default :
         break;
   }
   return jjStartNfa_0(7, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(7, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0, active1, 0L);
      return 9;
   }
   switch(curChar)
   {
      case 95:
         return jjMoveStringLiteralDfa10_0(active0, 0x80000000000L, active1, 0L);
      case 66:
      case 98:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x400000000000L);
      case 69:
      case 101:
         if ((active1 & 0x20000000L) != 0L)
            return jjStartNfaWithStates_0(9, 93, 11);
         break;
      case 79:
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0L, active1, 0x400000000000000L);
      case 84:
      case 116:
         if ((active0 & 0x4000000L) != 0L)
         {
            jjmatchedKind = 26;
            jjmatchedPos = 9;
         }
         return jjMoveStringLiteralDfa10_0(active0, 0x8002000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(8, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0, active1, 0L);
      return 10;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa11_0(active0, 0x2000L, active1, 0L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa11_0(active0, 0x80000000000L, active1, 0L);
      case 76:
      case 108:
         return jjMoveStringLiteralDfa11_0(active0, 0L, active1, 0x400000000000L);
      case 78:
      case 110:
         if ((active1 & 0x400000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 122, 68);
         break;
      case 83:
      case 115:
         if ((active0 & 0x8000000L) != 0L)
            return jjStartNfaWithStates_0(10, 27, 68);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa11_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(9, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(10, active0, active1, 0L);
      return 11;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         if ((active1 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(11, 110, 68);
         break;
      case 71:
      case 103:
         return jjMoveStringLiteralDfa12_0(active0, 0x2000L, active1, 0L);
      case 78:
      case 110:
         return jjMoveStringLiteralDfa12_0(active0, 0x80000000000L, active1, 0L);
      default :
         break;
   }
   return jjStartNfa_0(10, active0, active1, 0L);
}
private int jjMoveStringLiteralDfa12_0(long old0, long active0, long old1, long active1){
   if (((active0 &= old0) | (active1 &= old1)) == 0L)
      return jjStartNfa_0(10, old0, old1, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(11, active0, 0L, 0L);
      return 12;
   }
   switch(curChar)
   {
      case 69:
      case 101:
         return jjMoveStringLiteralDfa13_0(active0, 0x2000L);
      case 73:
      case 105:
         return jjMoveStringLiteralDfa13_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjStartNfa_0(11, active0, 0L, 0L);
}
private int jjMoveStringLiteralDfa13_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(11, old0, 0L, 0L);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(12, active0, 0L, 0L);
      return 13;
   }
   switch(curChar)
   {
      case 82:
      case 114:
         if ((active0 & 0x2000L) != 0L)
            return jjStartNfaWithStates_0(13, 13, 11);
         break;
      case 84:
      case 116:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(13, 43, 11);
         break;
      default :
         break;
   }
   return jjStartNfa_0(12, active0, 0L, 0L);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 68;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 138)
                        kind = 138;
                     { jjCheckNAddStates(0, 6); }
                  }
                  else if (curChar == 46)
                     { jjCheckNAddTwoStates(48, 58); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(45, 46); }
                  else if (curChar == 39)
                     { jjCheckNAddTwoStates(40, 41); }
                  else if (curChar == 58)
                     { jjAddStates(7, 9); }
                  else if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 68:
               case 11:
                  if ((0x3ff001800000000L & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  { jjCheckNAdd(11); }
                  break;
               case 69:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 138)
                        kind = 138;
                     { jjCheckNAdd(58); }
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 138)
                        kind = 138;
                     { jjCheckNAddTwoStates(48, 49); }
                  }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 147)
                        kind = 147;
                     { jjCheckNAddStates(10, 16); }
                  }
                  else if (curChar == 46)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 0:
                  if (curChar != 45)
                     break;
                  if (kind > 142)
                     kind = 142;
                  { jjCheckNAdd(1); }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) == 0L)
                     break;
                  if (kind > 142)
                     kind = 142;
                  { jjCheckNAdd(1); }
                  break;
               case 3:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 4:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 5:
                  if (curChar == 42)
                     { jjCheckNAddStates(17, 19); }
                  break;
               case 6:
                  if ((0xffff7bffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(7, 5); }
                  break;
               case 7:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(7, 5); }
                  break;
               case 8:
                  if (curChar == 47 && kind > 143)
                     kind = 143;
                  break;
               case 9:
                  if (curChar == 47)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 12:
                  if (curChar == 58)
                     { jjAddStates(7, 9); }
                  break;
               case 14:
                  if ((0x3ff001800000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjAddStates(20, 21); }
                  break;
               case 15:
                  if (curChar == 46)
                     jjstateSet[jjnewStateCnt++] = 16;
                  break;
               case 17:
                  if ((0x3ff001800000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  jjstateSet[jjnewStateCnt++] = 17;
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(19); }
                  break;
               case 20:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(20, 21); }
                  break;
               case 21:
                  if (curChar == 46)
                     { jjCheckNAdd(22); }
                  break;
               case 22:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(22); }
                  break;
               case 23:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(23, 24); }
                  break;
               case 25:
                  if ((0x280000000000L & l) != 0L)
                     { jjAddStates(22, 23); }
                  break;
               case 26:
                  if (curChar == 46)
                     { jjCheckNAdd(27); }
                  break;
               case 27:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(27); }
                  break;
               case 28:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddStates(24, 26); }
                  break;
               case 29:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(29); }
                  break;
               case 30:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(30, 31); }
                  break;
               case 31:
                  if (curChar == 46)
                     { jjCheckNAdd(32); }
                  break;
               case 32:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(32); }
                  break;
               case 33:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddStates(27, 29); }
                  break;
               case 34:
                  if (curChar == 46)
                     { jjCheckNAdd(35); }
                  break;
               case 35:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(35, 24); }
                  break;
               case 36:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 37:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(37); }
                  break;
               case 38:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(38, 24); }
                  break;
               case 39:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 40:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 41:
                  if (curChar != 39)
                     break;
                  if (kind > 148)
                     kind = 148;
                  jjstateSet[jjnewStateCnt++] = 42;
                  break;
               case 42:
                  if (curChar == 39)
                     { jjCheckNAddTwoStates(43, 41); }
                  break;
               case 43:
                  if ((0xffffff7fffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(43, 41); }
                  break;
               case 44:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 45:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(45, 46); }
                  break;
               case 46:
                  if (curChar == 34 && kind > 149)
                     kind = 149;
                  break;
               case 47:
                  if (curChar == 46)
                     { jjCheckNAddTwoStates(48, 58); }
                  break;
               case 48:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddTwoStates(48, 49); }
                  break;
               case 50:
                  if ((0x280000000000L & l) != 0L)
                     { jjAddStates(30, 31); }
                  break;
               case 51:
                  if (curChar == 46)
                     { jjCheckNAdd(52); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(52); }
                  break;
               case 53:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddStates(32, 34); }
                  break;
               case 54:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(54); }
                  break;
               case 55:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddTwoStates(55, 56); }
                  break;
               case 56:
                  if (curChar == 46)
                     { jjCheckNAdd(57); }
                  break;
               case 57:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(57); }
                  break;
               case 58:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(58); }
                  break;
               case 59:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddStates(0, 6); }
                  break;
               case 60:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddTwoStates(60, 49); }
                  break;
               case 61:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddStates(35, 37); }
                  break;
               case 62:
                  if (curChar == 46)
                     { jjCheckNAdd(63); }
                  break;
               case 63:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddTwoStates(63, 49); }
                  break;
               case 64:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAddTwoStates(64, 65); }
                  break;
               case 65:
                  if (curChar == 46)
                     { jjCheckNAdd(66); }
                  break;
               case 66:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(66); }
                  break;
               case 67:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 138)
                     kind = 138;
                  { jjCheckNAdd(67); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 2:
               case 10:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 68:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     { jjCheckNAdd(11); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 144)
                        kind = 144;
                     { jjCheckNAddTwoStates(10, 11); }
                  }
                  break;
               case 18:
               case 13:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddStates(38, 40); }
                  break;
               case 1:
                  if (kind > 142)
                     kind = 142;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 6:
               case 7:
                  { jjCheckNAddTwoStates(7, 5); }
                  break;
               case 11:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 144)
                     kind = 144;
                  { jjCheckNAdd(11); }
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(14, 15); }
                  break;
               case 16:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAddTwoStates(16, 17); }
                  break;
               case 17:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 147)
                     kind = 147;
                  { jjCheckNAdd(17); }
                  break;
               case 24:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(41, 43); }
                  break;
               case 40:
                  { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 43:
                  { jjCheckNAddTwoStates(43, 41); }
                  break;
               case 45:
                  { jjAddStates(44, 45); }
                  break;
               case 49:
                  if ((0x2000000020L & l) != 0L)
                     { jjAddStates(46, 48); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 1:
                  if ((jjbitVec0[i2] & l2) == 0L)
                     break;
                  if (kind > 142)
                     kind = 142;
                  jjstateSet[jjnewStateCnt++] = 1;
                  break;
               case 4:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(4, 5); }
                  break;
               case 6:
               case 7:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(7, 5); }
                  break;
               case 40:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(40, 41); }
                  break;
               case 43:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjCheckNAddTwoStates(43, 41); }
                  break;
               case 45:
                  if ((jjbitVec0[i2] & l2) != 0L)
                     { jjAddStates(44, 45); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 68 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}
static final int[] jjnextStates = {
   60, 61, 62, 49, 64, 65, 67, 13, 18, 36, 19, 20, 21, 23, 33, 34, 
   24, 5, 6, 8, 14, 15, 26, 28, 29, 30, 31, 33, 34, 24, 51, 53, 
   54, 55, 56, 61, 62, 49, 13, 14, 15, 25, 26, 28, 45, 46, 50, 51, 
   53, 
};

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, null, null, null, 
null, null, null, null, null, null, null, null, null, null, null, "\72", "\56", 
"\75", "\73", "\50", "\51", "\54", "\72\75", null, null, "\74\74", "\76\76", 
"\56\56", "\53", "\55", "\174\174", "\52", "\57", "\52\52", "\45", "\41", "\43", "\76", 
"\74", "\100", "\75\76", "\56\52", };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   final int beginLine;
   final int endLine;
   final int beginColumn;
   final int endColumn;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   beginLine = input_stream.getBeginLine();
   beginColumn = input_stream.getBeginColumn();
   endLine = input_stream.getEndLine();
   endColumn = input_stream.getEndColumn();
   t = Token.newToken(jjmatchedKind, curTokenImage);

   t.beginLine = beginLine;
   t.endLine = endLine;
   t.beginColumn = beginColumn;
   t.endColumn = endColumn;

   return t;
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token specialToken = null;
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(java.io.IOException e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      matchedToken.specialToken = specialToken;
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         matchedToken.specialToken = specialToken;
         return matchedToken;
      }
      else
      {
         if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
         {
            matchedToken = jjFillToken();
            if (specialToken == null)
               specialToken = matchedToken;
            else
            {
               matchedToken.specialToken = specialToken;
               specialToken = (specialToken.next = matchedToken);
            }
         }
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public PlSqlTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public PlSqlTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream)
  {
    jjmatchedPos = jjnewStateCnt = 0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 68; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }

/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};
static final long[] jjtoToken = {
   0xffffffffffffffe1L, 0xffffffffffffffffL, 0x1fffffff907ffL, 
};
static final long[] jjtoSkip = {
   0x1eL, 0x0L, 0xc000L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 0xc000L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[68];
    private final int[] jjstateSet = new int[2 * 68];

    
    protected char curChar;
}
