/* Generated By:JavaCC: Do not edit this line. PlSqlTreeConstants.java Version 6.0_1 */
package parser;

public interface PlSqlTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTBINDVARIABLE = 1;
  public int JJTALTERSESSION = 2;
  public int JJTDECLARATIONSECTION = 3;
  public int JJTDECLARATIONS = 4;
  public int JJTIDENTIFIERDECLARATION = 5;
  public int JJTCURSORDECLARATION = 6;
  public int JJTPRAGMADECLARATION = 7;
  public int JJTPROCEDUREDECLARATION = 8;
  public int JJTPROCEDUREBODY = 9;
  public int JJTFUNCTIONDECLARATION = 10;
  public int JJTFUNCTIONBODY = 11;
  public int JJTVARIABLEDECLARATION = 12;
  public int JJTCONSTANTDECLARATION = 13;
  public int JJTTYPEDEFINITION = 14;
  public int JJTBASICDATATYPEDEFINITION = 15;
  public int JJTEXCEPTIONDECLARATION = 16;
  public int JJTBEGINENDBLOCK = 17;
  public int JJTSEQUENCEOFSTATEMENTS = 18;
  public int JJTEXCEPTIONBLOCK = 19;
  public int JJTEXCEPTIONHANDLER = 20;
  public int JJTPLSQLSTATEMENT = 21;
  public int JJTLABELDECLARATION = 22;
  public int JJTFORALLSTATEMENT = 23;
  public int JJTSQLSTATEMENT = 24;
  public int JJTPROCEDURECALL = 25;
  public int JJTPROCEDUREREFERENCE = 26;
  public int JJTASSIGNMENTSTATEMENT = 27;
  public int JJTEXITSTATEMENT = 28;
  public int JJTGOTOSTATEMENT = 29;
  public int JJTIFSTATEMENT = 30;
  public int JJTLOOPSTATEMENT = 31;
  public int JJTNORMALLOOP = 32;
  public int JJTWHILELOOP = 33;
  public int JJTFORLOOP = 34;
  public int JJTNUMERICFORLOOPLOOKAHEAD = 35;
  public int JJTNUMERICFORLOOP = 36;
  public int JJTCURSORFORLOOP = 37;
  public int JJTCURSORREFERENCE = 38;
  public int JJTNULLSTATEMENT = 39;
  public int JJTRAISESTATEMENT = 40;
  public int JJTRETURNSTATEMENT = 41;
  public int JJTCLOSESTATEMENT = 42;
  public int JJTCOMMITSTATEMENT = 43;
  public int JJTFETCHSTATEMENT = 44;
  public int JJTLOCKTABLESTATEMENT = 45;
  public int JJTOPENSTATEMENT = 46;
  public int JJTROLLBACKSTATEMENT = 47;
  public int JJTSETSTATEMENT = 48;
  public int JJTLOCKMODE = 49;
  public int JJTSAVEPOINTSTATEMENT = 50;
  public int JJTUPDATESTATEMENT = 51;
  public int JJTRETURNINGCLAUSE = 52;
  public int JJTCOLUMNVALUES = 53;
  public int JJTCOLUMNVALUE = 54;
  public int JJTINSERTSTATEMENT = 55;
  public int JJTMERGESTATEMENT = 56;
  public int JJTMERGESETCOLUMN = 57;
  public int JJTDELETESTATEMENT = 58;
  public int JJTQUERYSTATEMENT = 59;
  public int JJTPLSQLEXPRESSION = 60;
  public int JJTPLSQLANDEXPRESSION = 61;
  public int JJTPLSQLUNARYLOGICALEXPRESSION = 62;
  public int JJTPLSQLRELATIONALEXPRESSION = 63;
  public int JJTPLSQLEXPRESSIONLIST = 64;
  public int JJTPLSQLINCLAUSE = 65;
  public int JJTPLSQLBETWEENCLAUSE = 66;
  public int JJTPLSQLLIKECLAUSE = 67;
  public int JJTISNULLCLAUSE = 68;
  public int JJTPLSQLSIMPLEEXPRESSION = 69;
  public int JJTPLSQLMULTIPLICATIVEEXPRESSION = 70;
  public int JJTPLSQLEXPONENTEXPRESSION = 71;
  public int JJTPLSQLUNARYEXPRESSION = 72;
  public int JJTPLSQLPRIMARYEXPRESSION = 73;
  public int JJTTABLECOLUMN = 74;
  public int JJTORACLEOBJECTNAME = 75;
  public int JJTTNSNAME = 76;
  public int JJTRELOP = 77;
  public int JJTTABLENAME = 78;
  public int JJTPARAMETERLIST = 79;
  public int JJTNUMORID = 80;
  public int JJTPARAMETER = 81;
  public int JJTARGUMENTS = 82;
  public int JJTARGUMENT = 83;
  public int JJTSELECTSTATEMENT = 84;
  public int JJTSELECTWITHOUTORDER = 85;
  public int JJTSELECTSET = 86;
  public int JJTSELECT = 87;
  public int JJTSELECTLIST = 88;
  public int JJTSELECTITEM = 89;
  public int JJTSELECTITEMALIAS = 90;
  public int JJTANALYTICFUNCTION = 91;
  public int JJTANALYTICCLAUSE = 92;
  public int JJTQUERYPARTITIONCLAUSE = 93;
  public int JJTWINDOWINGCLAUSE = 94;
  public int JJTINTOCLAUSE = 95;
  public int JJTDATAITEM = 96;
  public int JJTFROMCLAUSE = 97;
  public int JJTTABLEREFERENCE = 98;
  public int JJTQUERYTABLEEXPRESSION = 99;
  public int JJTTABLECOLLECTIONEXPRESSION = 100;
  public int JJTJOIN = 101;
  public int JJTJOINTYPE = 102;
  public int JJTCOLUMNNAME = 103;
  public int JJTWHERECLAUSE = 104;
  public int JJTCONNECTCLAUSE = 105;
  public int JJTGROUPBYCLAUSE = 106;
  public int JJTHAVINGCLAUSE = 107;
  public int JJTORDERBYCLAUSE = 108;
  public int JJTORDERBYEXPRESSION = 109;
  public int JJTFORUPDATECLAUSE = 110;
  public int JJTSQLEXPRESSION = 111;
  public int JJTSQLANDEXPRESSION = 112;
  public int JJTSQLUNARYLOGICALEXPRESSION = 113;
  public int JJTEXISTSCLAUSE = 114;
  public int JJTSQLRELATIONALEXPRESSION = 115;
  public int JJTSQLEXPRESSIONLIST = 116;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 117;
  public int JJTSQLINCLAUSE = 118;
  public int JJTSQLBETWEENCLAUSE = 119;
  public int JJTSQLLIKECLAUSE = 120;
  public int JJTSQLSIMPLEEXPRESSION = 121;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 122;
  public int JJTSQLEXPONENTEXPRESSION = 123;
  public int JJTSQLUNARYEXPRESSION = 124;
  public int JJTSQLPRIMARYEXPRESSION = 125;
  public int JJTSQLCASEEXPRESSION = 126;
  public int JJTSQLCASTEXPRESSION = 127;
  public int JJTINTERVALEXPRESSION = 128;
  public int JJTFUNCTIONCALL = 129;
  public int JJTFUNCTIONREFERENCE = 130;
  public int JJTFUNCTIONARGUMENTLIST = 131;
  public int JJTFUNCTIONARGUMENT = 132;
  public int JJTTRIMARGUMENTS = 133;
  public int JJTDATETIMEFIELD = 134;
  public int JJTOBJECTREFERENCE = 135;
  public int JJTOUTERJOINEXPRESSION = 136;
  public int JJTSUBQUERY = 137;
  public int JJTID = 138;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "BindVariable",
    "AlterSession",
    "DeclarationSection",
    "Declarations",
    "IdentifierDeclaration",
    "CursorDeclaration",
    "PragmaDeclaration",
    "ProcedureDeclaration",
    "ProcedureBody",
    "FunctionDeclaration",
    "FunctionBody",
    "VariableDeclaration",
    "ConstantDeclaration",
    "TypeDefinition",
    "BasicDataTypeDefinition",
    "ExceptionDeclaration",
    "BeginEndBlock",
    "SequenceOfStatements",
    "ExceptionBlock",
    "ExceptionHandler",
    "PLSQLStatement",
    "LabelDeclaration",
    "ForallStatement",
    "SQLStatement",
    "ProcedureCall",
    "ProcedureReference",
    "AssignmentStatement",
    "ExitStatement",
    "GotoStatement",
    "IfStatement",
    "LoopStatement",
    "NormalLoop",
    "WhileLoop",
    "ForLoop",
    "NumericForLoopLookahead",
    "NumericForLoop",
    "CursorForLoop",
    "CursorReference",
    "NullStatement",
    "RaiseStatement",
    "ReturnStatement",
    "CloseStatement",
    "CommitStatement",
    "FetchStatement",
    "LockTableStatement",
    "OpenStatement",
    "RollbackStatement",
    "SetStatement",
    "LockMode",
    "SavepointStatement",
    "UpdateStatement",
    "ReturningClause",
    "ColumnValues",
    "ColumnValue",
    "InsertStatement",
    "MergeStatement",
    "MergeSetColumn",
    "DeleteStatement",
    "QueryStatement",
    "PlSqlExpression",
    "PlSqlAndExpression",
    "PlSqlUnaryLogicalExpression",
    "PlSqlRelationalExpression",
    "PlSqlExpressionList",
    "PlSqlInClause",
    "PlSqlBetweenClause",
    "PlSqlLikeClause",
    "IsNullClause",
    "PlSqlSimpleExpression",
    "PlSqlMultiplicativeExpression",
    "PlSqlExponentExpression",
    "PlSqlUnaryExpression",
    "PlSqlPrimaryExpression",
    "TableColumn",
    "OracleObjectName",
    "TNSName",
    "Relop",
    "TableName",
    "ParameterList",
    "NumOrID",
    "Parameter",
    "Arguments",
    "Argument",
    "SelectStatement",
    "SelectWithoutOrder",
    "SelectSet",
    "Select",
    "SelectList",
    "SelectItem",
    "SelectItemAlias",
    "AnalyticFunction",
    "AnalyticClause",
    "QueryPartitionClause",
    "WindowingClause",
    "IntoClause",
    "DataItem",
    "FromClause",
    "TableReference",
    "QueryTableExpression",
    "TableCollectionExpression",
    "Join",
    "JoinType",
    "ColumnName",
    "WhereClause",
    "ConnectClause",
    "GroupByClause",
    "HavingClause",
    "OrderByClause",
    "OrderByExpression",
    "ForUpdateClause",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLExponentExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "SQLCaseExpression",
    "SQLCastExpression",
    "IntervalExpression",
    "FunctionCall",
    "FunctionReference",
    "FunctionArgumentList",
    "FunctionArgument",
    "TrimArguments",
    "DatetimeField",
    "ObjectReference",
    "OuterJoinExpression",
    "SubQuery",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=7f5b9d655bda21b28acfc73482e672ba (do not edit this line) */
